### ISSUE TITLE
Can't seem to install?

### ISSUE THREAD

**Issue by Oridjinn1980** [HtheChemist/BitBurnerCentralManager#1]
I'm following your instructions for installing, but it seems like it just doesn't work. Wget works fine and I get install.js on my Home server. After running install.js I get:
"Starting Boot.js
Getting started with the scripts. Please wait while we download. 
Version: 1
Quick start information:
run /CentralManager/Boot.js
....
Spawning /CentralMemory/Boot.js"

At this point, it gives a runtime error, with the contents:
"/CentralMemory/Boot.js@home
Failed to resolve module specifier "Constants.js". Relative references must start with either "/", "./", or "../".
stack:
TypeError: Failed to resolve module specifier "Constants.js". Relative references must start with either "/", "./", or "../"."

Not sure what's causing this or what can be done to fix it, but let me know if you need more info.

**Comment by Oridjinn1980** [comment]
I think the problem is with your imports. Your install script puts everything into a CentralMemory/ folder, but you don't have any of that in the script. If I add /CentralMemory/ to from "Constants.js", Boot.js will run separately from the install script. If I remove it again, it errors out.

Edit: Changing usrDirectory in install.js to const usrDirectory = ""; fixes the issues, and everything is able to start and run.

**Comment by HtheChemist** [comment]
Yes, thanks for the bug report. I will correct it today with some improvement.

**Comment by HtheChemist** [comment]
Updated, it should work now
