### ISSUE TITLE
No hacks after augmentation installed

### ISSUE THREAD

**Issue by schlaubi69** [HtheChemist/BitBurnerCentralManager#11]
Started after a new augumentaion install but the Hackmanager only gives this three lines:

> Picking a hack
> Getting available threads: 11
> No hack successfully started

Seems like something is not working on start with n00dles and foodnstuff.

If I start with Servermanager it buys some servers and now has more available threads but doesn't hack:

> Picking a hack
> Getting available threads: 19
> No hack successfully started

Targetmanager finds n00dles and foodnstuff as target, they are nuked, so far the things work.

Did manual hacks on n00dles and joesguns, some where about hacklevel 50 the Hackmanager started to work

**Comment by HtheChemist** [comment]
Hmm strange. What was your home server ram?

**Comment by schlaubi69** [comment]
I have 2.05 TB Homeserver. 
Nuking n00dles an foodnstuff by th Orchestrator brought me to hacking level 4.
My Multipliers
> Hacking Chance multiplier: | 167.50%
> 
> Hacking Speed multiplier: | 163.86%
> Hacking Money multiplier: | 543.41%
> Hacking Growth multiplier: | 253.96%

Perhaps it works with more augmentations, something happend after I had hacking level 54.

**Comment by HtheChemist** [comment]
I think I know what is happening.

During hack selection it check if you have at least 50% of the required thread for a fully executed hack. Probably that with a low hacking level, the amount of required thread is more than twice what you have at restart:

```
if (neededThreads <= availableThreads*0.5) {
	// Start the hack
	if (await startHack(topHack)) {
		hackSentSuccess = true
		break
	}
}
```

My guess is that I would need to make a better check for this part, maybe as simple as if there is no hack go through anyway.

**Comment by schlaubi69** [comment]
Then it may reallly be dependent from hacking level 50, then enough servers are opened that enough threads are available. Perhaps something simple that does the hacks below level 50 and then only if you have at least 50% of requiered hacks.
At the start with n00dles and foodnstuff there ar 11 threads available without bought servers.

**Comment by HtheChemist** [comment]
Corrected in the new version, it will now calculate the hack based on the available threads instead of the ideal amount.
