### ISSUE TITLE
Thread manager dies because inUse is not defined

### ISSUE THREAD

**Issue by lsv** [HtheChemist/BitBurnerCentralManager#13]
Ill give more info in a few days :)

**Comment by HtheChemist** [comment]
I had this happen in a previous version. Does it still happen in the newer version?

**Comment by gthazmatt** [comment]
I'm getting it after just running the TL;DR instructions.
![image](https://user-images.githubusercontent.com/1056858/149718105-3f3ecf9c-4a06-4a31-af9f-7fc17bba818b.png)

**Comment by HtheChemist** [comment]
Pretty sure I found the bug. Line 122 of ThreadManager.ts should read:

`if (threadIndex>=0) threads[threadIndex].inUse = false`

Will update tonight

instead of:

`if (threadIndex) threads[threadIndex].inUse = false`

**Comment by HtheChemist** [comment]
Update pushed, it should not happen anymore.
