### ISSUE TITLE
Couldn't start script on server

### ISSUE THREAD

**Issue by flightdragonz** [HtheChemist/BitBurnerCentralManager#14]
![threadError](https://user-images.githubusercontent.com/11172202/149926491-9e8bf773-41f0-42f7-9693-88df19463aa0.PNG)
Hi, I get this error after running the script for a while..

**Comment by HtheChemist** [comment]
what is the output of `run /Orchestrator/Console.js threadsUse`?

**Comment by flightdragonz** [comment]
Sorry, just updated the scripts and reset my game(installed some augment) , the issue was as of yesterday's commit, not sure if it's still happening in the current commit, ill keep you updated if it occurs again

**Comment by flightdragonz** [comment]
![image](https://user-images.githubusercontent.com/11172202/149961869-55087ab9-5fa4-4c40-9403-f5b877ad0f5a.png)
![image](https://user-images.githubusercontent.com/11172202/149961943-6f13d679-6795-4783-9a08-90e0026120a0.png)

Probably a minor bug with the script trying to start another thread on a server with maxed usage?

**Comment by HtheChemist** [comment]
Thanks, its is hard to say. I will need to eventually add more significant error message...

**Comment by HtheChemist** [comment]
I think that this is due to pre-existing server not having the right scripts on them, after an update for example. I have added in Boot.js  a small loop to copy the right file to the existing server.

**Comment by HtheChemist** [comment]
New update should solve this.
