### ISSUE TITLE
Failure to start with Boot.js

### ISSUE THREAD

**Issue by chrisblanton** [HtheChemist/BitBurnerCentralManager#17]
After the last update, the Boot.js is failing with the following error:
```
RUNTIME ERROR
/Orchestrator/Boot.js@home

Failed to resolve module specifier "/Orchestrator/MessageManager/enum". Invalid relative url or base scheme isn't hierarchical.
stack:
TypeError: Failed to resolve module specifier "/Orchestrator/MessageManager/enum". Invalid relative url or base scheme isn't hierarchical.
```

I tried with a completely fresh installation after manually deleting all the files in `/Orchestrator`, `/lib`, and `/resources`, however; I had the same error as above. 

Thank you for all your hard work!

**Comment by HtheChemist** [comment]
This is due to BitBurner last update, you need to save, then restart with killing all script.

**Comment by chrisblanton** [comment]
Thank you, that worked. I will add that to things to try in the future.
