### ISSUE TITLE
`npm run build` doesn't generate html

### ISSUE THREAD

**Issue by fschoenfeldt** [HtheChemist/BitBurnerCentralManager#20]
After working my way around https://github.com/HtheChemist/BitBurnerCentralManager/issues/19, I managed to run `npm build`, I started my webserver:

```
➜  BitBurnerCentralManager git:(master) ✗ npm run webserver

> webserver
> node bin/webserver.js -p 9182 -d build --enable_cors

Node Webserver running at port 9182
```

But upon visiting http://localhost:9182/, I get this error in my browser:
```
Error: ENOENT: no such file or directory, open 'build/index.html'
```

**Comment by HtheChemist** [comment]
It is expected, the server only serve the .js file for wget.
