### ISSUE TITLE
ServerManager.js

### ISSUE THREAD

**Issue by foopex** [HtheChemist/BitBurnerCentralManager#3]
buyServer() appears to hang here:
```
    async function buyServer(hostname, ram) {
        if (!hackPaused) {
            ns.print("Waiting");
            await messageHandler.sendMessage(ChannelName.hackManager, new Payload(Action.pause));
            await messageHandler.waitForAnswer();
        }
```

ServerManager.js Log
```
disableLog: Disabled logging for getServerMaxRam
Max server not hit
Waiting
```

I have reloaded with killing scripts and it still occurs.

**Comment by HtheChemist** [comment]
Yes I have spotted the problem. The HackManager would not answer correctly. The next update will have this corrected.

**Comment by klap50** [comment]
i try fix servermanager, but i dont have chance is to strong for my fool brain. :(

**Comment by HtheChemist** [comment]
The problem is solved in the next version (I will release it tonight).

The Hack Manager was not answer the pause request, hence it was always stuck.

**Comment by HtheChemist** [comment]
The update should solve this problem
