### ISSUE TITLE
Servermanager

### ISSUE THREAD

**Issue by schlaubi69** [HtheChemist/BitBurnerCentralManager#4]
Hi,
had 25 Servers with 16384 GB, after Start of boot.js in running game with >600b money.Servermanager started buying servers with several GB sizes, I think starting at 8GB, till 600b money were gone...

I think there is some check missing if there are already upgraded servers available. But positively, the Servermanager is now buying servers and upgrades them ;)

**Comment by schlaubi69** [comment]
My mistake, Servermanager worked fine, now I have 25 Servers with 262TB but no money ;) Perhaps there could be an option on boot-up if Serverupgrades are needed.

**Comment by HtheChemist** [comment]
No problem. You can use `run /Orchestrator/Boot.js no-server-manager` to disable the Server Manager at boot.
